source 'https://github.com/CocoaPods/Specs.git'

target 'JPAttributedString', :exclusive => true do
  pod "JPAttributedString", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JPAttributedString", :path => "../"

  pod 'Expecta', '~> 0.3.2'
  pod 'Specta', '~> 0.3.2'
end
