platform :ios, '9.0'

use_frameworks!
target 'JPAttributedString_Tests' do
  pod 'JPAttributedString', :path => '../'
  
  pod 'Quick', '~> 1.3.2'
  pod 'Nimble', '~> 7.3.1'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
        end
    end
end