language: objective-c

os: osx
osx_image: xcode10.1

script:
- pod install --project-directory=Example/
- xcodebuild -workspace Example/JPAttributedString.xcworkspace -scheme JPAttributedString-Example -sdk iphonesimulator12.1 -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.1' build test

notifications:
  email: false
