language: objective-c

before_install:
    - gem install cocoapods
    - pod install

osx_image: xcode8.2

xcode_workspace: JPAttributedString.xcworkspace
xcode_scheme: JPAttributedString-Example
xcode_sdk:
    - iphonesimulator10.2

notifications:
  email: false
