language: objective-c

os: osx
osx_image: xcode9

script:
- xcodebuild -workspace Example/JPAttributedString.xcworkspace -scheme JPAttributedString-Example -sdk iphonesimulator11.0 -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.0' build test

notifications:
  email: false
